#!/bin/bash
#PBS -N DMLTXXOUTPUTXX
#PBS -P dx2
#PBS -l ncpus=28
#PBS -l mem=126GB
#PBS -l walltime=01:00:00
#PBS -l jobfs=10GB
#PBS -l wd
#PBS -l storage=gdata/xp65+gdata/e14+scratch/e14
#PBS -q normal

module purge
module use /g/data/xp65/public/modules
module load conda/analysis3-25.06

# XOUTPUTX -> output to process

python3 -c "$(cat << EOF

import xarray as xr
import numpy as np
import os
from tqdm import tqdm
from dask.distributed import Client

client = Client(n_workers=28)

# Settings and paths:
output = XXOUTPUTXX

base = '/scratch/e14/rmh561/access-om2/archive/025deg_jra55_iaf_cycle6_online_mlt/'
tmp_folder = base + 'post_processed_diags/'

base2 = base + 'output%03d/ocean/' % output
reg = [None,None,None,None] # Globe
times = slice(None,None)
times_snap = slice(None,None) # Note; this must be 1 more than times.

chunks2D = {'time':1,'yt_ocean':216,'xt_ocean':240}

ds_grid = xr.open_dataset(base2 + 'ocean_grid.nc',chunks=chunks2D).sel(xt_ocean=slice(reg[0],reg[1]),yt_ocean=slice(reg[2],reg[3]))#.isel(time=times)
rho0 = 1035.
Cp = 3992.10322329649

# Load falling average daily budget diagnostics (note that the "_risavg" is a misnomer - they are falling averages):
ds_day_budget = xr.open_dataset(base2 + 'ocean_budget_daily_risavg.nc',decode_times=False,chunks=chunks2D).sel(xt_ocean=slice(reg[0],reg[1]),yt_ocean=slice(reg[2],reg[3]))

# Fix time variable by decoding time by hand (see https://forum.access-hive.org.au/t/cftime-vs-datetime64-time-encoding-issues-with-access-om2-025-omip-2-run/4085);
ds_day_budget = ds_day_budget.assign_coords({'time':[np.datetime64('0001-01-01') + np.timedelta64(int(x*86400),'s') for x in ds_day_budget.time.values]})

# Fix average_DT by decoding by hand:
ds_day_budget.average_DT.data = ds_day_budget.average_DT*np.timedelta64(1,'D')

# Subselect time period:
ds_day_budget = ds_day_budget.sel(time=times)

bud_tendency = 'temp_tendency_in_mld_cor'
bud_var_grps = {'advection':['temp_advection_in_mld_cor',
                             'temp_submeso_in_mld',
                             'neutral_diffusion_in_mld_temp',
                             'neutral_gm_in_mld_temp',
                             'temp_vdiffuse_k33_in_mld'],
                'vert_mixing':['temp_nonlocal_KPP_in_mld',
                               'temp_vdiffuse_diff_cbt_in_mld'],
                'surface_flux':['temp_rivermix_in_mld',
                                'temp_vdiffuse_sbc_in_mld', 
                                'frazil_3d_in_mld',
                                'sfc_hflux_pme_in_mld_cor',
                                'temp_eta_smooth_in_mld_cor'], 
                'sw_pen':['sw_heat_in_mld']}
bud_var_extras = {'shortwave':['swflx_in_mld'],
                  'longwave':['lw_heat_in_mld'],
                  'sensible':['sens_heat_in_mld'],
                  'latent':['evap_heat_in_mld']}

def compute_corrections(ds_day_budget):

    # P-E+R correction: 
    pme_cor = -ds_day_budget['pme_river_times_temp_in_mld']/rho0
    ds_day_budget['sfc_hflux_pme_in_mld_cor'] = ds_day_budget['sfc_hflux_pme_in_mld'] + pme_cor*rho0*Cp

    # Eta-smoother correction:
    eta_smoother_cor = -ds_day_budget['eta_smoother_times_temp_in_mld']/rho0
    ds_day_budget['temp_eta_smooth_in_mld_cor'] = ds_day_budget['temp_eta_smooth_in_mld'] + eta_smoother_cor*rho0*Cp

    # Advection correction:
    adv_cor1 = (-ds_day_budget['eta_t_tendency_times_temp_in_mld'] + ds_day_budget['pme_river_times_temp_in_mld'] + ds_day_budget['eta_smoother_times_temp_in_mld'])/rho0
    adv_cor2 = ds_day_budget['s_surf_ent_temp']/rho0
    ds_day_budget['temp_advection_in_mld_cor'] = ds_day_budget['temp_advection_in_mld'] + adv_cor1*rho0*Cp  + adv_cor2*rho0*Cp

    # Total correction for entrainment-by-residual:
    ds_day_budget['temp_tendency_in_mld_cor'] = ds_day_budget['temp_tendency_in_mld']  + pme_cor*rho0*Cp + adv_cor1*rho0*Cp + adv_cor2*rho0*Cp + eta_smoother_cor*rho0*Cp

    return(ds_day_budget)

def mlt_budget_fixedh(ds_day_budget, do_extras = True):

    # Divisor to apply to all terms.
    # Note that the division by average_DT in seconds fixes a bug in the 
    # normalization of the daily falling average diagnostics
    divisor = rho0*Cp*ds_day_budget.average_DT/np.timedelta64(1,'s')

    # Extract variable sums in groups, dividing by rho0*Cp to convert to degC/second
    mlt_budget = (ds_day_budget[bud_tendency]/divisor).rename('fixedh_tendency').to_dataset()
    for var in bud_var_grps.keys():
        mlt_budget[var] = ds_day_budget[bud_var_grps[var][0]]/divisor
        if (len(bud_var_grps[var])>1):
            for raw_var in bud_var_grps[var][1:]:
                mlt_budget[var] += ds_day_budget[raw_var]/divisor
    
    # Compute residual for check:
    mlt_budget['residual'] = mlt_budget['fixedh_tendency'].copy(deep=True)
    for var in list(mlt_budget.data_vars):
        mlt_budget['residual'] -= mlt_budget[var]

    if do_extras:
        for var in bud_var_extras.keys():
            mlt_budget[var] = ds_day_budget[bud_var_extras[var][0]]/divisor
            if (len(bud_var_extras[var])>1):
                for raw_var in bud_var_extras[var][1:]:
                    mlt_budget[var] += ds_day_budget[raw_var]/divisor

    return(mlt_budget)

ds_day_budget = compute_corrections(ds_day_budget)

# Compute in blocks (e.g. if doing a whole year):

# NOTE: THIS still seems way slower than it should be... Something simple might make it faster...
bs = 30; tl = len(ds_day_budget.time)
blocks = [range(tl)[x*bs:(x+1)*bs] for x in range(int(np.ceil(tl/bs)))]
blocks_snap = [range(tl+1)[x*bs:(x+1)*bs + 1] for x in range(int(np.ceil(tl/bs)))]

mlt_budget_falavg_daily_uncat = []
for i in tqdm(range(len(blocks))):
    bud = mlt_budget_fixedh(ds_day_budget.isel(time=blocks[i]))
    mlt_budget_falavg_daily_uncat.append(bud.load())
mlt_budget_falavg_daily = xr.concat(mlt_budget_falavg_daily_uncat,dim='time')

# Save to file if desired:
fname = tmp_folder + 'mlt_budget_falavg_daily_online_output%03d.nc' % output
mlt_budget_falavg_daily.to_netcdf(fname)

# Create monthly means from daily files and save back to file:
ds  = xr.open_dataset(fname, chunks={'time':61, 'yt_ocean': 180, 'xt_ocean': 240})
ds_mon = xr.zeros_like(ds.resample(time='1ME').mean()).copy(deep=True)

for var in tqdm(ds.data_vars):
    ds_mon[var] = ds[var].resample(time='1ME').mean().load()
ds_mon = ds_mon.assign_coords({'time':ds.time.resample(time='1ME').mean()})
ds_mon.to_netcdf(fname[:-3] + '_monthly_mean.nc')

# Remove daily file to save space:
# os.remove(fname)

EOF
)"
